### ISSUE TITLE
bad request 400 error

### ISSUE THREAD

**Issue by farukdemirel** [chuacw/ElasticSearchIndexDelphi#1]
I am trying to evaluate your code
Using Delphi 10.1, with elasticsearch-5.3.0 at windows 10.

http://localhost:9200/ and
http://localhost:9200/_settings URLs are working via chrome browser.

But I am getting bad request 400 error at line.
 FHTTP.Put(LURL, LStream)
when I executed the code.

What would be the problem? Any help appreciated.
Thanks.

**Comment by chuacw** [comment]
Hi there,

When you say getting bad request 400 error at line, what line is it?

**Comment by farukdemirel** [comment]
After the
LElasticSearch.NumReplica[''] := 0;
line, it goes to the TElasticSearch.SetNumReplica method... Image below.

![image](https://cloud.githubusercontent.com/assets/20535332/25150987/89419bf0-248c-11e7-9e28-87b06e51d795.png)

**Comment by chuacw** [comment]
Thanks! I've made updates. Please retest with the new update.

**Comment by farukdemirel** [comment]
Thank you. RESTComponent unit Needed to compile this commit.

Regards.

**Comment by farukdemirel** [comment]
Thank you for adding restcomponet.pas.
I still can't execute due to the error 404 now but let me figure out that I am doing a mistake or not. I will write again.

**Comment by farukdemirel** [comment]
Hi, I am still in trouble with GET method. 
![image](https://cloud.githubusercontent.com/assets/20535332/25382551/d25e397c-29c0-11e7-844a-be8f4fa78acc.png). The URL: "http://localhost:9200/_xpack/security/user/"
is getting response from browser but "404 error" occurs within code.

it passes the GET line with an ordinary www address like below.
LURL := 'http://www.google.com.tr'

Any suggestion?

**Comment by cheeweee** [comment]
What response are you getting from the browser http://localhost:9200/_xpack/security/user/ ? Screenshot from browser is appreciated.

**Comment by farukdemirel** [comment]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_xpack","index_uuid":"_na_","index":"_xpack"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_xpack","index_uuid":"_na_","index":"_xpack"},"status":404}

**Comment by chuacw** [comment]
This is because you do not have X-Pack installed.

You'll need to install X-Pack using Elasticsearch.

bin\elasticsearch-plugin install x-pack

**Comment by chuacw** [comment]
Install X-Pack
